--1. What is the total revenue generated by male vs. female customers?
select 
gender,
sum(purchase_amount) as revenue
from
customer
group by gender

--2. Which customers used a discount but still spent more than the average purchase amount? 
select 
customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--3. Which are the top 5 products with the highest average review rating?
select top 5
item_purchased,
round(avg(review_rating),2) as review_rating
from customer
group by  item_purchased
order by avg(review_rating) desc

--4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select 
shipping_type,
round(avg(purchase_amount),2) as average_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select 
count(customer_id) as total_customers,
subscription_status,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg(purchase_amount),sum(purchase_amount) desc

--6. Which 5 products have the highest percentage of purchases with discounts applied?
select
top 5
item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

--7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with cte as(
	select 
	customer_id,
	previous_purchases,
	case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
	from customer
)
select 
customer_segment,
count(*) as total_customers
from cte
group by customer_segment
order by total_customers desc

--8. What are the top 3 most purchased products within each category?
with cte as(
	select
	category,
	item_purchased,
	count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id) desc) as rk
	from customer
	group by category, item_purchased
)
select 
rk,
category,
item_purchased,
total_orders
from cte
where rk <= 3

--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10. What is the revenue contribution of each age group?
select
age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
